name: Team Generator

on:
  issue_comment:
    types: [ created ]

jobs:
  comment:
    if: contains(github.event.comment.body, 'team generator')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Test
        run: |
          python3 run.py >> $GITHUB_ENV
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.MESSAGE }} A
#          body:
          reactions: 'heart'